/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void home_button_click(GImageButton source, GEvent event) { //_CODE_:home_button:581349:
  currentPage = "home";
} //_CODE_:home_button:581349:

public void my_cart_button_click1(GImageButton source, GEvent event) { //_CODE_:my_cart_button:649753:
  currentPage = "cart";
  
  subtotal = 0;
  // Calculate subtotal
  for (Product p : productsInCart) {
    subtotal += p.price * p.quantity;
  }


} //_CODE_:my_cart_button:649753:

public void ProfileButton_click(GImageButton source, GEvent event) { //_CODE_:ProfileButton:415454:
  //println("ProfileButton - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:ProfileButton:415454:

public void RFSButton_clicked(GButton source, GEvent event) { //_CODE_:RFSButton:727323:
  hasRainforestSupreme = true;
  invisible_controls();
  RFSButton.setVisible(false);

} //_CODE_:RFSButton:727323:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:900822:
  // RainForest logo picture
  currentPage = "home";
} //_CODE_:imgButton1:900822:

public void supreme_deals_button_click1(GButton source, GEvent event) { //_CODE_:supreme_deals_button:437597:
  println("supreme_deals_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:supreme_deals_button:437597:

public void Shop_click1(GButton source, GEvent event) { //_CODE_:Shop_button:327819:
  currentPage = "shop";
  println("shop pressed");
  //println( Shop_button.
} //_CODE_:Shop_button:327819:

public void dollar_button_click1(GImageButton source, GEvent event) { //_CODE_:dollar_button:718026:
  money += 1000;
} //_CODE_:dollar_button:718026:

public void sales_button_click1(GButton source, GEvent event) { //_CODE_:sales_button:865886:
  currentPage = "sales";
} //_CODE_:sales_button:865886:

public void shippingOptionsButtonClicked(GButton source, GEvent event) { //_CODE_:shippingOptionsButton:842274:
  currentPage = "shippingOptions";
} //_CODE_:shippingOptionsButton:842274:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  home_button = new GImageButton(this, 21, 16, 78, 75, new String[] { "homebuttonimg.png", "homebuttonimg.png", "homebuttonimg.png" } );
  home_button.addEventHandler(this, "home_button_click");
  my_cart_button = new GImageButton(this, 597, 36, 100, 60, new String[] { "checkoutbuttonimg.png", "checkoutbuttonimg.png", "checkoutbuttonimg.png" } );
  my_cart_button.addEventHandler(this, "my_cart_button_click1");
  ProfileButton = new GImageButton(this, 699, 36, 100, 60, new String[] { "profilepng.png", "profilepng.png", "profilepng.png" } );
  ProfileButton.addEventHandler(this, "ProfileButton_click");
  RFSButton = new GButton(this, -3, 519, 115, 83);
  RFSButton.setText("Upgrade to RainForest Supreme");
  RFSButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  RFSButton.addEventHandler(this, "RFSButton_clicked");
  imgButton1 = new GImageButton(this, 298, 0, 208, 99, new String[] { "rainforestlogopng.png", "rainforestlogopng.png", "rainforestlogopng.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  supreme_deals_button = new GButton(this, 325, 314, 150, 85);
  supreme_deals_button.setText("RainForestSupreme deals");
  supreme_deals_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  supreme_deals_button.addEventHandler(this, "supreme_deals_button_click1");
  Shop_button = new GButton(this, 325, 195, 150, 85);
  Shop_button.setText("SHOP");
  Shop_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  Shop_button.addEventHandler(this, "Shop_click1");
  dollar_button = new GImageButton(this, 676, 507, 123, 93, new String[] { "dollarimg.png", "dollarimg.png", "dollarimg.png" } );
  dollar_button.addEventHandler(this, "dollar_button_click1");
  sales_button = new GButton(this, 323, 442, 150, 85);
  sales_button.setText("Sales");
  sales_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  sales_button.addEventHandler(this, "sales_button_click1");
  shippingOptionsButton = new GButton(this, 667, 557, 80, 30);
  shippingOptionsButton.setText("Next");
  shippingOptionsButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  shippingOptionsButton.addEventHandler(this, "shippingOptionsButtonClicked");
}

// Variable declarations 
// autogenerated do not edit
GImageButton home_button; 
GImageButton my_cart_button; 
GImageButton ProfileButton; 
GButton RFSButton; 
GImageButton imgButton1; 
GButton supreme_deals_button; 
GButton Shop_button; 
GImageButton dollar_button; 
GButton sales_button; 
GButton shippingOptionsButton; 
